---

- name: Install web packages
  yum: name={{item}} state=present
  tags: install
  with_items:
  - ImageMagick
  - memcached
  - httpd
  - php56w
  - php56w-soap
  - php56w-mcrypt
  - php56w-xml
  - php56w-mbstring
  - php56w-mysql
  - php56w-curl
  - php56w-gd
  - php56w-pecl-memcached
  - php56w-pecl-xdebug
  - php56w-pecl-apcu
  - php-drush-drush
  - phpmyadmin
  - mod_ssl
  - openssl
  #- varnish
  #- newrelic-php5
  #- php-pear   # Installs pecl command
  #- php-devel  # Required for pecl install
  #- memcached-devel # Required for "pecl install memcache"

- name: Allow everyone to read http logs
  file: state=directory path=/var/log/httpd owner=root group=root mode=0755

- name: Setup | Disable default apache welcome site
  file: state=absent path=/etc/httpd/conf.d/welcome.conf
  notify: Restart Apache

- include: ../tasks/centos-selfsigned.yml

- name: Configure | Apache default configuration
  template: src=apache-httpd-conf.j2 dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644
  notify: Restart Apache
  tags: configure

#- name: Configure | Apache extra configuration
#  template: src=apache-conf.j2 dest=/etc/httpd/conf.d/sff.conf owner=root group=root mode=0644
#  notify: Restart Apache
#  tags: configure

- name: Configure | WWW sites configuration
  template: src=apache-sites-conf.j2 dest=/etc/httpd/conf.d/sites.conf owner=root group=root mode=0644
  notify: Restart Apache
  tags: configure

- name: Configure | Remove old PHP configuration
  file: state=absent path=/etc/php.d/sff.ini
  tags: configure
- name: Configure | PHP configuration
  template: src=php-ini.j2 dest=/etc/php.d/vagrant.ini owner=root group=root mode=0644
  notify: Restart Apache
  tags: configure

- name: Configure | PhpMyAdmin configuration
  template: src=apache-phpmyadmin-conf.j2 dest=/etc/httpd/conf.d/phpMyAdmin.conf owner=root group=root mode=0644
  notify: Restart Apache
  tags: configure

- include: ../tasks/catchmail-script.yml
#- include: ../tasks/mailcatcher.yml
- include: ../tasks/debug.yml

- name: Start Services
  service: name={{item}} state=started enabled=true
  with_items:
  #- varnish
  - memcached
  - httpd

# FILE DOWNLOAD

# Cant use built in synchronize command since there's no way to speciy a different ssh user with delegate_to or a specific private key
#- name: Rsync uploaded files
#  synchronize: src={{item.1.remote_source_path}} dest=/vagrant/sites/{{item.0.host}}/{{item.1.local_target_path}}
#    archive=no times=yes recursive=yes mode=pull
#  with_subelements:
#  - sites
#  - rsync

- name: Download uploaded files to virtual machine (this will take a while)
  command: rsync -rti -e 'ssh -i {{private_key_dir}}/{{item.1.ssh_private_key}} -o StrictHostKeyChecking=no' {{item.1.ssh_user}}@{{item.1.ssh_host}}:{{item.1.remote_source_path}} /vagrant/sites/{{item.0.host}}/{{item.1.local_target_path}}
  with_subelements:
  - sites
  - rsync
  when: item.1.ssh_host is defined
  tags:
  - sync
  - configure
  register: rsync_result
  changed_when: rsync_result.stdout != ""
