---

extra_repos:
- dest: /tmp/epel-release.rpm
  url: http://mirror.nsc.liu.se/fedora-epel/6/i386/epel-release-6-8.noarch.rpm
- dest: /tmp/webtatic-el6.rpm
  url: https://mirror.webtatic.com/yum/el6/latest.rpm
#- { dest: '/tmp/newrelic-repo.rpm', url: 'http://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm' }
#- { dest: '/tmp/varnish-repo.rpm', url: 'http://repo.varnish-cache.org/redhat/varnish-3.0/el6/noarch/varnish-release/varnish-release-3.0-1.el6.noarch.rpm' }
#- { dest: '/tmp/epel-release.rpm', url: 'http://dl.iuscommunity.org/pub/ius/stable/CentOS/5/x86_64/epel-release-5-4.noarch.rpm' }
#- { dest: '/tmp/ius-release.rpm', url: 'http://dl.iuscommunity.org/pub/ius/stable/CentOS/5/x86_64/ius-release-1.0-11.ius.centos5.noarch.rpm' }

database_root_user: root 
database_root_pass: vagrant 

sites_dir: /vagrant/sites
database_host: localhost

apache_log_dir: /var/log/httpd

private_key_dir: /privatekeys

php_memory: 400M
php_upload: 50M